### ISSUE TITLE
Bug when calling strrpos()

### ISSUE THREAD

**Issue by maxguru** [heiglandreas/Org_Heigl_Ghostscript#13]
You have the two arguments reversed on the following line,

https://github.com/heiglandreas/Org_Heigl_Ghostscript/blob/master/src/Ghostscript.php#L886

According to the docs, haystack comes first,

https://secure.php.net/manual/en/function.strrpos.php

**Comment by heiglandreas** [comment]
Thanks for spotting!

I've just fixed that and created a new release
