### ISSUE TITLE
Remove Ghostscript::setGsPath() in Ghostscript.php

### ISSUE THREAD

**Issue by jannejava** [heiglandreas/Org_Heigl_Ghostscript#4]
Sorry, the last line in Ghostscript.php

       Ghostscript::setGsPath();

 ...makes it impossible to set an alternative path for gs. Otherwise the package seems really nice!

**Comment by heiglandreas** [comment]
That last line causes the Ghostscript-library to set a default path. It will be executed once when the file is included. After that you should be able to set a different GS-Path using ```Ghostscript::setGsPath('/path/to/other/gs');``` 

So something like this should work:
```php
    use Org_Heigl\Ghostscript\Ghostscript;

    $gs = new Ghostscript() // needed to trigger loading the class
    Ghostscript::setGsPath('/path/to/different/gs');
    $gs->render('/path/to/file');
```

Calling ```Ghostscript::setGsPath('/new/path/to/gs')``` should be sufficient to set the path new as the file will be loaded and interpreted (therefore the call to setGsPath at the end of the file will be executed there) before calling ```setGsPath()``` (again) with the new path.

(Not tested ATM - will do so later today)

**Comment by jannejava** [comment]
Thanks for your quick reply! 

I understand the motivation behind this but it's causing a catch 22 problem.

If you look at `function setGsPath()`: If `$path` is not specified, it assumes that `exec("which gs")` will find something otherwise an error is thrown. I have my gs-command installed at a custom location and `exec("which gs")` returns null from PHP. 

So, once Ghostscript.php is autoloaded the static function `setGsPath()` is executed (at the end of the file) with `$path = null` that triggers `exec("which gs")` that breaks the PHP-execution, and I will never get passed this point and be able to set the path manually.

If you have command gs installed at a location where will PHP find it, that is the only time you will be able to set a custom path, as I can see this.

`public static function setGsPath($path = null)
    {
        if (null === $path) {
            $path = exec('which gs', $output);
            if (! $output) {
                throw new \UnexpectedValueException('No Ghostscript-instance found or running on windows. Please provide Path to the Ghostscript-executable');
            }
            $path = $output[0];
        }
        if ($path) {
            self::$PATH = $path;
        }
        return self::$PATH;
    }`

**Comment by heiglandreas** [comment]
Ahhhh!!!! I see what you mean! :frowning_face: 

Looks like I need to fix that! Easiest fix for you would be to either remove the last line from Ghostscript.php or put that line into a ```try-catch```-block that does nothing within the catch like this:

```php
    try {
        Ghostscript::setGsPath();
    } catch (\Exception $e) {
    }
```

A proper solution will be added later today. Expect a new release later today!

And also **Thanks for spotting and raising an issue!!**

**Comment by jannejava** [comment]
No worries! 👍 

I just removed the last line and I have it working.

**Comment by heiglandreas** [comment]
Thanks for reporting! The [new release](https://github.com/heiglandreas/Org_Heigl_Ghostscript/releases/tag/2.2.1) should fix this issue. 

Feel free to open new issues should problems arise ;)

**Comment by rafauel** [comment]
I have the same problem and I don't know how to solve it, I downloaded the newest version.

`  ///opt/ghostpdl-9.53.3/bin/gs
        $gs = new Ghostscript();
        Ghostscript::setGsPath('/var/www/vendor/org_heigl/');
        $gs->setDevice('jpeg')
            ->setInputFile('https://appbk.s3.sa-east-1.amazonaws.com/2022/08/3683f47a-5712-4ac6-802d-0ae258c43398.pdf')
            ->setResolution(150)
            ->setTextAntiAliasing(Ghostscript::ANTIALIASING_HIGH)
            ->setOutputFile($guid . '%d');

        if (true === $gs->render()) :
            for ($i = 1; $i <= $paginas; $i++) :
                $arquivoImagem[] = ['nome' => $guid . $i, 'diretorio' => $paginas_path . '/', 'extensao' => $extensao, 'pagina' => $i];
            endfor;
            return $arquivoImagem;
        else :
            return false;
        endif;`

what should the setGsPath path look like?

I put a random path. Well, I don't know which way to go.

**Comment by heiglandreas** [comment]
Let me dig into that....

**Comment by rafauel** [comment]
How can I talk to you to show the problem?

**Comment by rafauel** [comment]
If that's the case I pay to help me solve this, I really need it.

**Comment by heiglandreas** [comment]
The string provided in the method `setGsPath` is the path to the Ghostscript executable.

As you seem to have Ghostscript in the non-standard location `/opt/ghostpdl-9.53.3/bin/gs`, exactly this path needs to be provided.

So your script should look as follows:

```php

// First we need to create a local file from the remote one.
// Check out the AWS SDK, there are possibly better solutions to that than this ;-)
$filename = tempnam('pdf', sys_get_temp_dir());

$localHandle = fopen($filename, "w");
$remoteHandle = fopen('https://appbk.s3.sa-east-1.amazonaws.com/2022/08/3683f47a-5712-4ac6-802d-0ae258c43398.pdf', 'r');
if (FALSE === $remoteHandle) {
    exit("Failed to open stream to URL");
}

while (!feof($remoteHandle)) {
    fwrite($localHandle, fread($handle, 8192));
}
fclose($remoteHandle);
fclose($localHandle);

// Run the Lib
$gs = new Ghostscript();
Ghostscript::setGsPath('/opt/ghostpdl-9.53.3/bin/gs');
$gs->setDevice('jpeg')
   ->setInputFile($filename)
   ->setResolution(150)
   ->setTextAntiAliasing(Ghostscript::ANTIALIASING_HIGH)
   ->setOutputFile($guid . '%d');

if (true === $gs->render()) {
    for ($i = 1; $i <= $paginas; $i++) {
        $arquivoImagem[] = ['nome' => $guid . $i, 'diretorio' => $paginas_path . '/', 'extensao' => $extensao, 'pagina' => $i];
    }
    return $arquivoImagem;
}
// As you are returning in the `if`-part, you do not need the `else` ;-)
return false;
```

**Comment by rafauel** [comment]
No, it's not the executable path.

I didn't even know I needed it.

I'm using Laravel, inside a docker.

How could I put this path to this executable you mentioned?

**Comment by heiglandreas** [comment]
Ghostscript only runs on local files! So the file needs to be available on the machine that runs the script. If - like in your case - the file is on AWS you need to create a local copy.

**Comment by heiglandreas** [comment]
If that doesn't solve the issue, drop me an email at andreas AT heigl.org

**Comment by rafauel** [comment]
`ErrorException: tempnam(): file created in the system's temporary directory in file /var/www/app/Http/Controllers/api/ApiController.php on line 90
`

I ran it and the return I got

**Comment by rafauel** [comment]
Where can I find the email so we can talk?

**Comment by heiglandreas** [comment]
Looks like that is something with laravel. Using `@tempnam` instead of `tempnam` seems to fix the issue... See for example https://github.com/Glavin001/atom-beautify/issues/1108 

Oh. And `tempnam` requires the arguments the other way round: So 

```php
$filename = @tempnam(sys_get_temp_dir(), 'pdf');
```

**Comment by heiglandreas** [comment]
> Where can I find the email so we can talk?

See end of https://github.com/heiglandreas/Org_Heigl_Ghostscript/issues/4#issuecomment-1231878952 :wink:

**Comment by rafauel** [comment]
Your name @ the right domain?

**Comment by rafauel** [comment]
I sent the email. confirm if it arrived.
Thank you for your patience so far.

**Comment by heiglandreas** [comment]
Email was confirmed. Please also check your spam folder
