### ISSUE TITLE
Question: get the number of pages

### ISSUE THREAD

**Issue by freekmurze** [heiglandreas/Org_Heigl_Ghostscript#5]
Is there a method that returns the number of pages in the pdf?

**Comment by heiglandreas** [comment]
Currently not. And TBH that's not really in the scope of a Ghostscript-Wrapper.

After spending some time searching through packagist I think there's a lib missing that allows retrieval of "simple" metadata from a PDF-file using plain PHP. So I might throw something together that allows that should need arise ;)
